version: '3.8'

services:
  web:
    build: .
    container_name: creator-metrics-api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:Lzk83232@db:5432/metrics_db
    depends_on:
      - db
    networks:
      - metrics-network

  db:
    image: postgres:13
    container_name: metrics-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=metrics_db
      - POSTGRES_PASSWORD=Lzk83232
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    networks:
      - metrics-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: metrics-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - metrics-network

volumes:
  postgres_data:

networks:
  metrics-network:
    driver: bridge